language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run build --prod

before_deploy:
  - cd dist
  
deploy:
  provider: s3
  access_key_id: AKIAJVF46MNZ7SUUD5IQ
  secret_access_key:
    secure: Nhgj2i4vUuB7uz2CvBbdz2njTx396ytRtdzMLUAFOFwfYLxvUoQabSgb33jqfdMvk7ws7Mv/6P6ythki0hj8ZHKS98x2cdOcCAOh8c8fiJZlXhLYKcg6cp3NO4GIekJjPF36f3622bg2HcjiMPfaj31rqY0Sv7RekPva+UDLwslZAHGlDJ9LszzqsAAPOM5sCfHUXevzSxsKRXNwkcJgPRejTdIh6wFPJct8mMzMaRC6Q4D4qWcrvkuLJlhRYggr89bByb6vyt5PoDNXo36nbcxrLCYzvPwsDKVxCBN0Wk/qxJMj8wgGdU4jq8qgqWj3gP+vXpRsXW7hsiGgnjLtjW0Ged5Pg1xqggQptDn6XuVeZ4hlkPZzj4w36wkWhHir6lQT7hN/ckMiTjLQtwkFFQmGPu+aFIdNhbcypIpDw7ebXmUriehLQRtL6OFN/ygHvPM7zLDWDsV7yRuudT76iUTU33zX3Zn2cgRftPTqhR0YDr1BiaAOOZfvh9c9cgz9w0EiTCzs1KLescoieYI8+d45eNDXdResLt9jbSjr0e/Pda7bGGGf2U2XQoKO/7nNEIl0K2PMjTbsonOWqbisvTiVw4lKGvPDLcydBjCjunhml8Ib2NAzER2SlyP2g5XG20UZBsiBOA2lshDVXN6M7QkZ7IaU18S4zgFH1mA3sWQ=
  bucket: www.unas.io
  region: us-east-2
  skip_cleanup: true
  acl: public_read
  upload-dir: app